* Simulation configuration

** Notes

- You can validate a simulation configuration against the schema using
  one of the many free online tools:
  + https://www.liquid-technologies.com/online-json-schema-validator
- =simulation-hyperparameters.contemporaneous_sample= should be =true=
  for a contemporaneous sample and =false= for serial sampling (the
  default value). If there is serial sampling, the
  =simulation-hyperparameters.sampling_prop_bounds= is used as the
  sampling proportion given removal. If there is a contemporaneous
  sample, this is the probability of an extant lineage being included
  in the sample.
- =simulation-hyperparameters.report-temporal-data= can be set to
  =true= in order to capture temporal data from the simulation in the
  resulting database (=false= by default). If this parameter is set
  to =true=, =simulation-hyperparameters.num-temp-measurements= (an
  =integer=) must also be specified. This is the number of randomly
  selected time points between the start of the epidemic and the
  present at which data is reported.

** Schema

#+begin_src json :tangle simulation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "simulation-name": {
      "type": "string"
    },
    "output-hdf5": {
      "type": "string"
    },
    "seed": {
      "type": "integer"
    },
    "remaster-xml": {
      "type": "string"
    },
    "num-simulations": {
      "type": "integer"
    },
    "num-workers": {
      "type": "integer"
    },
    "simulation-hyperparameters": {
      "type": "object",
      "properties": {
        "duration-range": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            },
            {
              "type": "integer"
            }
          ]
        },
        "num-changes": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            },
            {
              "type": "integer"
            }
          ]
        },
        "shrinkage-factor": {
          "type": "number"
        },
        "r0_bounds": {
          "type": "array",
          "items": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ]
        },
        "net_rem_rate_bounds": {
          "type": "array",
          "items": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ]
        },
        "sampling_prop_bounds": {
          "type": "array",
          "items": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ]
        },
        "contemporaneous_sample": {
          "type": "boolean"
        },
        "report-temporal-data": {
            "type": "boolean"
        },
        "num-temp-measurements": {
            "type": "integer"
        }
      },
      "required": [
        "duration-range",
        "num-changes",
        "shrinkage-factor",
        "r0_bounds",
        "net_rem_rate_bounds",
        "sampling_prop_bounds",
      ]
    }
  },
  "required": [
    "simulation-name",
    "output-hdf5",
    "seed",
    "remaster-xml",
    "num-simulations",
    "simulation-hyperparameters"
  ]
}
#+end_src
